# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: jab.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "AscendantLocator",
    "ClickElementRequest",
    "ClickElementResponse",
    "DescendantLocator",
    "Element",
    "FindElementsRequest",
    "FindElementsResponse",
    "GetElementFromHandleRequest",
    "GetElementFromHandleResponse",
    "GetVersionInfoRequest",
    "GetVersionInfoResponse",
    "IndexLocator",
    "JabServiceStub",
    "ListJavaWindowsRequest",
    "ListJavaWindowsResponse",
    "Locator",
    "ReadTableRequest",
    "ReadTableResponse",
    "RefreshTreeRequest",
    "RefreshTreeResponse",
    "SelectWindowRequest",
    "SelectWindowResponse",
    "StringLocator",
    "Table",
    "TableCell",
    "TableRow",
    "TypeTextRequest",
    "TypeTextResponse",
    "VersionInfo",
    "WaitUntilElementExistsRequest",
    "WaitUntilElementExistsResponse",
    "WindowInfo",
)

from dataclasses import dataclass

import betterproto2
import grpc

from ..message_pool import default_message_pool

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False)
class AscendantLocator(betterproto2.Message):
    locator: "Locator | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    is_parent: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)


default_message_pool.register_message("jab", "AscendantLocator", AscendantLocator)


@dataclass(eq=False, repr=False)
class ClickElementRequest(betterproto2.Message):
    handle: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)


default_message_pool.register_message("jab", "ClickElementRequest", ClickElementRequest)


@dataclass(eq=False, repr=False)
class ClickElementResponse(betterproto2.Message):
    success: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)

    error_message: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message(
    "jab", "ClickElementResponse", ClickElementResponse
)


@dataclass(eq=False, repr=False)
class DescendantLocator(betterproto2.Message):
    locator: "Locator | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    is_child: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)


default_message_pool.register_message("jab", "DescendantLocator", DescendantLocator)


@dataclass(eq=False, repr=False)
class Element(betterproto2.Message):
    handle: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)

    name: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    role: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)

    states: "list[str]" = betterproto2.field(4, betterproto2.TYPE_STRING, repeated=True)

    states_en_us: "list[str]" = betterproto2.field(
        5, betterproto2.TYPE_STRING, repeated=True
    )

    description: "str" = betterproto2.field(6, betterproto2.TYPE_STRING)

    text: "str" = betterproto2.field(7, betterproto2.TYPE_STRING)

    x: "int" = betterproto2.field(8, betterproto2.TYPE_INT32)

    y: "int" = betterproto2.field(9, betterproto2.TYPE_INT32)

    width: "int" = betterproto2.field(10, betterproto2.TYPE_INT32)

    height: "int" = betterproto2.field(11, betterproto2.TYPE_INT32)

    accessible_action: "bool" = betterproto2.field(12, betterproto2.TYPE_BOOL)

    accessible_text: "bool" = betterproto2.field(13, betterproto2.TYPE_BOOL)

    accessible_selection: "bool" = betterproto2.field(14, betterproto2.TYPE_BOOL)

    children_count: "int" = betterproto2.field(15, betterproto2.TYPE_INT32)

    index_in_parent: "int" = betterproto2.field(16, betterproto2.TYPE_INT32)

    children_handles: "list[int]" = betterproto2.field(
        17, betterproto2.TYPE_UINT64, repeated=True
    )

    parent_handle: "int | None" = betterproto2.field(
        18, betterproto2.TYPE_UINT64, optional=True
    )

    depth: "int" = betterproto2.field(19, betterproto2.TYPE_INT32)


default_message_pool.register_message("jab", "Element", Element)


@dataclass(eq=False, repr=False)
class FindElementsRequest(betterproto2.Message):
    locator: "Locator | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("jab", "FindElementsRequest", FindElementsRequest)


@dataclass(eq=False, repr=False)
class FindElementsResponse(betterproto2.Message):
    elements: "list[Element]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )

    error_message: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message(
    "jab", "FindElementsResponse", FindElementsResponse
)


@dataclass(eq=False, repr=False)
class GetElementFromHandleRequest(betterproto2.Message):
    handle: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)


default_message_pool.register_message(
    "jab", "GetElementFromHandleRequest", GetElementFromHandleRequest
)


@dataclass(eq=False, repr=False)
class GetElementFromHandleResponse(betterproto2.Message):
    element: "Element | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    error_message: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message(
    "jab", "GetElementFromHandleResponse", GetElementFromHandleResponse
)


@dataclass(eq=False, repr=False)
class GetVersionInfoRequest(betterproto2.Message):
    pass


default_message_pool.register_message(
    "jab", "GetVersionInfoRequest", GetVersionInfoRequest
)


@dataclass(eq=False, repr=False)
class GetVersionInfoResponse(betterproto2.Message):
    version_info: "VersionInfo | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    error_message: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message(
    "jab", "GetVersionInfoResponse", GetVersionInfoResponse
)


@dataclass(eq=False, repr=False)
class IndexLocator(betterproto2.Message):
    index: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)


default_message_pool.register_message("jab", "IndexLocator", IndexLocator)


@dataclass(eq=False, repr=False)
class ListJavaWindowsRequest(betterproto2.Message):
    pass


default_message_pool.register_message(
    "jab", "ListJavaWindowsRequest", ListJavaWindowsRequest
)


@dataclass(eq=False, repr=False)
class ListJavaWindowsResponse(betterproto2.Message):
    windows: "list[WindowInfo]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message(
    "jab", "ListJavaWindowsResponse", ListJavaWindowsResponse
)


@dataclass(eq=False, repr=False)
class Locator(betterproto2.Message):
    name: "StringLocator | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    role: "StringLocator | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )

    description: "StringLocator | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )

    text: "StringLocator | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True
    )

    has_state: "list[str]" = betterproto2.field(
        5, betterproto2.TYPE_STRING, repeated=True
    )

    not_has_state: "list[str]" = betterproto2.field(
        6, betterproto2.TYPE_STRING, repeated=True
    )

    index_in_parent: "IndexLocator | None" = betterproto2.field(
        7, betterproto2.TYPE_MESSAGE, optional=True
    )

    ascendant: "AscendantLocator | None" = betterproto2.field(
        8, betterproto2.TYPE_MESSAGE, optional=True
    )

    descendants: "list[DescendantLocator]" = betterproto2.field(
        9, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("jab", "Locator", Locator)


@dataclass(eq=False, repr=False)
class ReadTableRequest(betterproto2.Message):
    locator: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


default_message_pool.register_message("jab", "ReadTableRequest", ReadTableRequest)


@dataclass(eq=False, repr=False)
class ReadTableResponse(betterproto2.Message):
    table: "Table | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    error_message: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message("jab", "ReadTableResponse", ReadTableResponse)


@dataclass(eq=False, repr=False)
class RefreshTreeRequest(betterproto2.Message):
    pass


default_message_pool.register_message("jab", "RefreshTreeRequest", RefreshTreeRequest)


@dataclass(eq=False, repr=False)
class RefreshTreeResponse(betterproto2.Message):
    success: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)

    error_message: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message("jab", "RefreshTreeResponse", RefreshTreeResponse)


@dataclass(eq=False, repr=False)
class SelectWindowRequest(betterproto2.Message):
    window_info: "WindowInfo | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("jab", "SelectWindowRequest", SelectWindowRequest)


@dataclass(eq=False, repr=False)
class SelectWindowResponse(betterproto2.Message):
    success: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)

    error_message: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message(
    "jab", "SelectWindowResponse", SelectWindowResponse
)


@dataclass(eq=False, repr=False)
class StringLocator(betterproto2.Message):
    find: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    regex: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)


default_message_pool.register_message("jab", "StringLocator", StringLocator)


@dataclass(eq=False, repr=False)
class Table(betterproto2.Message):
    row_count: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)

    column_count: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)

    rows: "list[TableRow]" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, repeated=True
    )

    column_headers: "list[str]" = betterproto2.field(
        4, betterproto2.TYPE_STRING, repeated=True
    )


default_message_pool.register_message("jab", "Table", Table)


@dataclass(eq=False, repr=False)
class TableCell(betterproto2.Message):
    value: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    row: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)

    column: "int" = betterproto2.field(3, betterproto2.TYPE_INT32)


default_message_pool.register_message("jab", "TableCell", TableCell)


@dataclass(eq=False, repr=False)
class TableRow(betterproto2.Message):
    cells: "list[TableCell]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("jab", "TableRow", TableRow)


@dataclass(eq=False, repr=False)
class TypeTextRequest(betterproto2.Message):
    handle: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)

    text: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message("jab", "TypeTextRequest", TypeTextRequest)


@dataclass(eq=False, repr=False)
class TypeTextResponse(betterproto2.Message):
    success: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)

    error_message: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message("jab", "TypeTextResponse", TypeTextResponse)


@dataclass(eq=False, repr=False)
class VersionInfo(betterproto2.Message):
    vm_version: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    bridge_java_class_version: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    bridge_java_dll_version: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)

    bridge_win_dll_version: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)


default_message_pool.register_message("jab", "VersionInfo", VersionInfo)


@dataclass(eq=False, repr=False)
class WaitUntilElementExistsRequest(betterproto2.Message):
    locator: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    timeout_seconds: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)


default_message_pool.register_message(
    "jab", "WaitUntilElementExistsRequest", WaitUntilElementExistsRequest
)


@dataclass(eq=False, repr=False)
class WaitUntilElementExistsResponse(betterproto2.Message):
    exists: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)

    error_message: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message(
    "jab", "WaitUntilElementExistsResponse", WaitUntilElementExistsResponse
)


@dataclass(eq=False, repr=False)
class WindowInfo(betterproto2.Message):
    hwnd: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)

    title: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message("jab", "WindowInfo", WindowInfo)


class JabServiceStub:
    def __init__(self, channel: grpc.Channel):
        self._channel = channel

    def list_java_windows(
        self, message: "ListJavaWindowsRequest | None" = None
    ) -> "ListJavaWindowsResponse":
        if message is None:
            message = ListJavaWindowsRequest()

        return self._channel.unary_unary(
            "/jab.JabService/ListJavaWindows",
            ListJavaWindowsRequest.SerializeToString,
            ListJavaWindowsResponse.FromString,
        )(message)

    def select_window(self, message: "SelectWindowRequest") -> "SelectWindowResponse":
        return self._channel.unary_unary(
            "/jab.JabService/SelectWindow",
            SelectWindowRequest.SerializeToString,
            SelectWindowResponse.FromString,
        )(message)

    def refresh_tree(
        self, message: "RefreshTreeRequest | None" = None
    ) -> "RefreshTreeResponse":
        if message is None:
            message = RefreshTreeRequest()

        return self._channel.unary_unary(
            "/jab.JabService/RefreshTree",
            RefreshTreeRequest.SerializeToString,
            RefreshTreeResponse.FromString,
        )(message)

    def find_elements(self, message: "FindElementsRequest") -> "FindElementsResponse":
        return self._channel.unary_unary(
            "/jab.JabService/FindElements",
            FindElementsRequest.SerializeToString,
            FindElementsResponse.FromString,
        )(message)

    def get_element_from_handle(
        self, message: "GetElementFromHandleRequest"
    ) -> "GetElementFromHandleResponse":
        return self._channel.unary_unary(
            "/jab.JabService/GetElementFromHandle",
            GetElementFromHandleRequest.SerializeToString,
            GetElementFromHandleResponse.FromString,
        )(message)

    def click_element(self, message: "ClickElementRequest") -> "ClickElementResponse":
        return self._channel.unary_unary(
            "/jab.JabService/ClickElement",
            ClickElementRequest.SerializeToString,
            ClickElementResponse.FromString,
        )(message)

    def type_text(self, message: "TypeTextRequest") -> "TypeTextResponse":
        return self._channel.unary_unary(
            "/jab.JabService/TypeText",
            TypeTextRequest.SerializeToString,
            TypeTextResponse.FromString,
        )(message)

    def read_table(self, message: "ReadTableRequest") -> "ReadTableResponse":
        return self._channel.unary_unary(
            "/jab.JabService/ReadTable",
            ReadTableRequest.SerializeToString,
            ReadTableResponse.FromString,
        )(message)

    def wait_until_element_exists(
        self, message: "WaitUntilElementExistsRequest"
    ) -> "WaitUntilElementExistsResponse":
        return self._channel.unary_unary(
            "/jab.JabService/WaitUntilElementExists",
            WaitUntilElementExistsRequest.SerializeToString,
            WaitUntilElementExistsResponse.FromString,
        )(message)

    def get_version_info(
        self, message: "GetVersionInfoRequest | None" = None
    ) -> "GetVersionInfoResponse":
        """
        rpc SubscribeCallbacks(SubscribeCallbacksRequest) returns (stream CallbackEvent);
        """

        if message is None:
            message = GetVersionInfoRequest()

        return self._channel.unary_unary(
            "/jab.JabService/GetVersionInfo",
            GetVersionInfoRequest.SerializeToString,
            GetVersionInfoResponse.FromString,
        )(message)
