# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import jab_pb2 as jab__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jab_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JabServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListJavaWindows = channel.unary_unary(
                '/jab.JabService/ListJavaWindows',
                request_serializer=jab__pb2.ListJavaWindowsRequest.SerializeToString,
                response_deserializer=jab__pb2.ListJavaWindowsResponse.FromString,
                _registered_method=True)
        self.SelectWindowByTitle = channel.unary_unary(
                '/jab.JabService/SelectWindowByTitle',
                request_serializer=jab__pb2.SelectWindowByTitleRequest.SerializeToString,
                response_deserializer=jab__pb2.SelectWindowByTitleResponse.FromString,
                _registered_method=True)
        self.SelectWindowByPid = channel.unary_unary(
                '/jab.JabService/SelectWindowByPid',
                request_serializer=jab__pb2.SelectWindowByPidRequest.SerializeToString,
                response_deserializer=jab__pb2.SelectWindowByPidResponse.FromString,
                _registered_method=True)
        self.GetElements = channel.unary_unary(
                '/jab.JabService/GetElements',
                request_serializer=jab__pb2.GetElementsRequest.SerializeToString,
                response_deserializer=jab__pb2.GetElementsResponse.FromString,
                _registered_method=True)
        self.ClickElement = channel.unary_unary(
                '/jab.JabService/ClickElement',
                request_serializer=jab__pb2.ClickElementRequest.SerializeToString,
                response_deserializer=jab__pb2.ClickElementResponse.FromString,
                _registered_method=True)
        self.TypeText = channel.unary_unary(
                '/jab.JabService/TypeText',
                request_serializer=jab__pb2.TypeTextRequest.SerializeToString,
                response_deserializer=jab__pb2.TypeTextResponse.FromString,
                _registered_method=True)
        self.ReadTable = channel.unary_unary(
                '/jab.JabService/ReadTable',
                request_serializer=jab__pb2.ReadTableRequest.SerializeToString,
                response_deserializer=jab__pb2.ReadTableResponse.FromString,
                _registered_method=True)
        self.WaitUntilElementExists = channel.unary_unary(
                '/jab.JabService/WaitUntilElementExists',
                request_serializer=jab__pb2.WaitUntilElementExistsRequest.SerializeToString,
                response_deserializer=jab__pb2.WaitUntilElementExistsResponse.FromString,
                _registered_method=True)
        self.GetVersionInfo = channel.unary_unary(
                '/jab.JabService/GetVersionInfo',
                request_serializer=jab__pb2.GetVersionInfoRequest.SerializeToString,
                response_deserializer=jab__pb2.GetVersionInfoResponse.FromString,
                _registered_method=True)
        self.SubscribeCallbacks = channel.unary_stream(
                '/jab.JabService/SubscribeCallbacks',
                request_serializer=jab__pb2.SubscribeCallbacksRequest.SerializeToString,
                response_deserializer=jab__pb2.CallbackEvent.FromString,
                _registered_method=True)


class JabServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListJavaWindows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelectWindowByTitle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelectWindowByPid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetElements(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClickElement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TypeText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WaitUntilElementExists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersionInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeCallbacks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JabServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListJavaWindows': grpc.unary_unary_rpc_method_handler(
                    servicer.ListJavaWindows,
                    request_deserializer=jab__pb2.ListJavaWindowsRequest.FromString,
                    response_serializer=jab__pb2.ListJavaWindowsResponse.SerializeToString,
            ),
            'SelectWindowByTitle': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectWindowByTitle,
                    request_deserializer=jab__pb2.SelectWindowByTitleRequest.FromString,
                    response_serializer=jab__pb2.SelectWindowByTitleResponse.SerializeToString,
            ),
            'SelectWindowByPid': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectWindowByPid,
                    request_deserializer=jab__pb2.SelectWindowByPidRequest.FromString,
                    response_serializer=jab__pb2.SelectWindowByPidResponse.SerializeToString,
            ),
            'GetElements': grpc.unary_unary_rpc_method_handler(
                    servicer.GetElements,
                    request_deserializer=jab__pb2.GetElementsRequest.FromString,
                    response_serializer=jab__pb2.GetElementsResponse.SerializeToString,
            ),
            'ClickElement': grpc.unary_unary_rpc_method_handler(
                    servicer.ClickElement,
                    request_deserializer=jab__pb2.ClickElementRequest.FromString,
                    response_serializer=jab__pb2.ClickElementResponse.SerializeToString,
            ),
            'TypeText': grpc.unary_unary_rpc_method_handler(
                    servicer.TypeText,
                    request_deserializer=jab__pb2.TypeTextRequest.FromString,
                    response_serializer=jab__pb2.TypeTextResponse.SerializeToString,
            ),
            'ReadTable': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadTable,
                    request_deserializer=jab__pb2.ReadTableRequest.FromString,
                    response_serializer=jab__pb2.ReadTableResponse.SerializeToString,
            ),
            'WaitUntilElementExists': grpc.unary_unary_rpc_method_handler(
                    servicer.WaitUntilElementExists,
                    request_deserializer=jab__pb2.WaitUntilElementExistsRequest.FromString,
                    response_serializer=jab__pb2.WaitUntilElementExistsResponse.SerializeToString,
            ),
            'GetVersionInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersionInfo,
                    request_deserializer=jab__pb2.GetVersionInfoRequest.FromString,
                    response_serializer=jab__pb2.GetVersionInfoResponse.SerializeToString,
            ),
            'SubscribeCallbacks': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeCallbacks,
                    request_deserializer=jab__pb2.SubscribeCallbacksRequest.FromString,
                    response_serializer=jab__pb2.CallbackEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jab.JabService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jab.JabService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JabService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListJavaWindows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jab.JabService/ListJavaWindows',
            jab__pb2.ListJavaWindowsRequest.SerializeToString,
            jab__pb2.ListJavaWindowsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SelectWindowByTitle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jab.JabService/SelectWindowByTitle',
            jab__pb2.SelectWindowByTitleRequest.SerializeToString,
            jab__pb2.SelectWindowByTitleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SelectWindowByPid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jab.JabService/SelectWindowByPid',
            jab__pb2.SelectWindowByPidRequest.SerializeToString,
            jab__pb2.SelectWindowByPidResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetElements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jab.JabService/GetElements',
            jab__pb2.GetElementsRequest.SerializeToString,
            jab__pb2.GetElementsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClickElement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jab.JabService/ClickElement',
            jab__pb2.ClickElementRequest.SerializeToString,
            jab__pb2.ClickElementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TypeText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jab.JabService/TypeText',
            jab__pb2.TypeTextRequest.SerializeToString,
            jab__pb2.TypeTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jab.JabService/ReadTable',
            jab__pb2.ReadTableRequest.SerializeToString,
            jab__pb2.ReadTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WaitUntilElementExists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jab.JabService/WaitUntilElementExists',
            jab__pb2.WaitUntilElementExistsRequest.SerializeToString,
            jab__pb2.WaitUntilElementExistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVersionInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jab.JabService/GetVersionInfo',
            jab__pb2.GetVersionInfoRequest.SerializeToString,
            jab__pb2.GetVersionInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeCallbacks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/jab.JabService/SubscribeCallbacks',
            jab__pb2.SubscribeCallbacksRequest.SerializeToString,
            jab__pb2.CallbackEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
